### PR TITLE
Moved the apollo-fetch change log into its package.

### PR DESCRIPTION
**Pull request by jaydenseric**
Also tidied up the log to date.

TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by evanshauser** [comment]
@jaydenseric this is great, thank you for making this suggestion! I'm not sure the best way to organize the CHANGELOG.md's. Two thoughts are: have one per package with a universal log that points to each of the individual logs or have a single log with everything.

I think we should have a log per package, especially since we hope to have a bunch of packages running in parallel.

Also, to note `apollo-link` will have similar issues.

@jbaxleyiii what do you think?

**Comment by jaydenseric** [comment]
`readme.md` and `changelog.md` are [never ignored by npm](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) and are meant to be published in packages.

I suggest keeping readmes and changelogs in each package, and then in the main repo readme have a heading for each package with links to each readme and changelog.

**Comment by evanshauser** [comment]
Even better! I think we definitely should do per package readme/changelog then. Any blockers @jbaxleyiii?

**Comment by stubailo** [comment]
I like that idea then!

**Comment by jaydenseric** [comment]
@evanshauser can we please merge this now before other new PRs conflict again; a readme update can happen anytime later on a new PR.

**Comment by evanshauser** [comment]
@jaydenseric Done! Thank you for moving the changelog!

**Pull request merged**
