### PR TITLE
UMD support

### LINKED ISSUE #3: Feature idea: Unpkg CDN
https://unpkg.com/#/

For this to work all we need to do is publish a UMD to npm, similar to what we have in Apollo Client!

### PR DESCRIPTION
**Pull request by kamilkisiela**
Fixes #3

Use `/src` as the root directory. No more `/dist/src/index.js`, just `/dist/index.js`.
Create `/dist/bundle.umd.js`
Use `module`, `jsnext:main` for `/dist/index.js`
Use `main` for `/dist/bundle.umd.js`

Fix shadow variable `apolloFetch` in `/src/apollo-fetch.ts`

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@kamilkisiela thank you! @evanshauser this looks great to me! I don't want it to conflict with your learna work though, do you want me to merge this or wait and let you handle it?

**Comment by evanshauser** [comment]
@kamilkisiela Thank you so much for adding umd support! The repo is now converted over to lerna. I wasn't sure what the transition would look like, and now it seems that your changes would be almost drop into the apollo-fetch package! Could you rebase when you get a chance? Then I'll merge the changes in

**Comment by kamilkisiela** [comment]
@evanshauser @jbaxleyiii done

**Comment by evanshauser** [comment]
@kamilkisiela Great work, thank you for adding UMD support!

**Pull request merged**
